//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class rule_field_value
    {
        public int rule_field_value_id { get; set; }
        public int rule_field_map_id { get; set; }
        public int row_id { get; set; }
        public string value { get; set; }
        public sbyte active { get; set; }
        public System.DateTime date_added { get; set; }
        public string user_added { get; set; }
        public Nullable<System.DateTime> date_changed { get; set; }
        public string user_changed { get; set; }
    
        public virtual rule_field_map rule_field_map { get; set; }
    }
}
