//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class rule_field_map
    {
        public rule_field_map()
        {
            this.rule_field_value = new HashSet<rule_field_value>();
        }
    
        public int rule_field_map_id { get; set; }
        public int master_rule_id { get; set; }
        public int field_id { get; set; }
        public sbyte active { get; set; }
        public System.DateTime date_added { get; set; }
        public string user_added { get; set; }
        public Nullable<System.DateTime> date_changed { get; set; }
        public string user_changed { get; set; }
    
        public virtual field field { get; set; }
        public virtual master_rule master_rule { get; set; }
        public virtual ICollection<rule_field_value> rule_field_value { get; set; }
    }
}
