//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkSample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RulesEntities : DbContext
    {
        public RulesEntities()
            : base("name=RulesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<field> fields { get; set; }
        public DbSet<master_rule> master_rule { get; set; }
        public DbSet<rule_field_map> rule_field_map { get; set; }
        public DbSet<rule_field_value> rule_field_value { get; set; }

        [DbFunction("YouDbContext.Store", "YourScalarFunction")]
        public string YourScalarFunction(string parameter)
        {
            var lObjectContext = ((IObjectContextAdapter)this).ObjectContext;

            return lObjectContext.
                CreateQuery<string>(
                    "YouDbContext.Store.YourScalarFunction",
                    new ObjectParameter("parameterName", parameter)).
                Execute(MergeOption.NoTracking).
                FirstOrDefault();
        }
    }
}
